package internal

import (
	"errors"
	"testing"
)

// Note: Tests on this file are generated by LLM. I have checked
// each of these tests one by one but I still feel the need to
// mention this as a disclaimer
// --- NewFieldSelector tests ---

func TestNewFieldSelector_EmptyString(t *testing.T) {
	_, err := NewFieldSelector("")
	if !errors.Is(err, ErrFieldStrEmpty) {
		t.Errorf("expected ErrFieldStrEmpty, got %v", err)
	}
}

func TestNewFieldSelector_SingleField(t *testing.T) {
	fs, err := NewFieldSelector("1")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(fs.sorted) != 1 || fs.sorted[0] != 1 {
		t.Errorf("expected sorted=[1], got %v", fs.sorted)
	}
	if fs.maxField != 1 {
		t.Errorf("expected maxField=1, got %d", fs.maxField)
	}
}

func TestNewFieldSelector_MultipleFields(t *testing.T) {
	fs, err := NewFieldSelector("3,1,2")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expected := []int{1, 2, 3}
	for i, v := range fs.sorted {
		if v != expected[i] {
			t.Errorf("expected sorted=%v, got %v", expected, fs.sorted)
			break
		}
	}
	if fs.maxField != 3 {
		t.Errorf("expected maxField=3, got %d", fs.maxField)
	}
}

func TestNewFieldSelector_FieldZero(t *testing.T) {
	_, err := NewFieldSelector("0")
	if !errors.Is(err, ErrFieldBelowOne) {
		t.Errorf("expected ErrFieldBelowOne, got %v", err)
	}
}

func TestNewFieldSelector_NegativeField(t *testing.T) {
	_, err := NewFieldSelector("-1")
	if !errors.Is(err, ErrFieldBelowOne) {
		t.Errorf("expected ErrFieldBelowOne, got %v", err)
	}
}

func TestNewFieldSelector_InvalidFieldNonNumeric(t *testing.T) {
	_, err := NewFieldSelector("a")
	if err == nil {
		t.Error("expected error for non-numeric field, got nil")
	}
}

// --- Range tests ---

func TestNewFieldSelector_ValidRange(t *testing.T) {
	fs, err := NewFieldSelector("1-3")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expected := []int{1, 2, 3}
	for i, v := range fs.sorted {
		if v != expected[i] {
			t.Errorf("expected sorted=%v, got %v", expected, fs.sorted)
			break
		}
	}
	if fs.maxField != 3 {
		t.Errorf("expected maxField=3, got %d", fs.maxField)
	}
}

func TestNewFieldSelector_SingleValueRange(t *testing.T) {
	// "3-3" is a degenerate but valid range
	fs, err := NewFieldSelector("3-3")
	if err != nil {
		t.Fatalf("expected no error for single-value range, got %v", err)
	}
	if len(fs.sorted) != 1 || fs.sorted[0] != 3 {
		t.Errorf("expected sorted=[3], got %v", fs.sorted)
	}
}

func TestNewFieldSelector_RangeStartGreaterThanEnd(t *testing.T) {
	_, err := NewFieldSelector("3-1")
	if !errors.Is(err, ErrInvalidRange) {
		t.Errorf("expected ErrInvalidRange, got %v", err)
	}
}

func TestNewFieldSelector_RangeStartZero(t *testing.T) {
	_, err := NewFieldSelector("0-3")
	if !errors.Is(err, ErrFieldBelowOne) {
		t.Errorf("expected ErrFieldBelowOne, got %v", err)
	}
}

func TestNewFieldSelector_RangeEndZero(t *testing.T) {
	_, err := NewFieldSelector("1-0")
	if !errors.Is(err, ErrFieldBelowOne) {
		t.Errorf("expected ErrFieldBelowOne for end=0, got %v", err)
	}
}

func TestNewFieldSelector_NegativeRangeStart(t *testing.T) {
	// "-1-3" has a leading "-", caught by HasPrefix guard
	_, err := NewFieldSelector("-1-3")
	if !errors.Is(err, ErrFieldBelowOne) {
		t.Errorf("expected ErrFieldBelowOne, got %v", err)
	}
}

func TestNewFieldSelector_RangeTooManyParts(t *testing.T) {
	_, err := NewFieldSelector("1-2-3")
	if !errors.Is(err, ErrInvalidRangeFormat) {
		t.Errorf("expected ErrInvalidRangeFormat, got %v", err)
	}
}

func TestNewFieldSelector_RangeNonNumericStart(t *testing.T) {
	_, err := NewFieldSelector("a-3")
	if err == nil {
		t.Error("expected error for non-numeric range start, got nil")
	}
}

func TestNewFieldSelector_RangeNonNumericEnd(t *testing.T) {
	_, err := NewFieldSelector("1-b")
	if err == nil {
		t.Error("expected error for non-numeric range end, got nil")
	}
}

// --- Mixed fields and ranges ---

func TestNewFieldSelector_MixedFieldsAndRanges(t *testing.T) {
	fs, err := NewFieldSelector("1,3-5,7")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expected := []int{1, 3, 4, 5, 7}
	for i, v := range fs.sorted {
		if v != expected[i] {
			t.Errorf("expected sorted=%v, got %v", expected, fs.sorted)
			break
		}
	}
	if fs.maxField != 7 {
		t.Errorf("expected maxField=7, got %d", fs.maxField)
	}
}

func TestNewFieldSelector_MaxFieldTrackedAcrossMixed(t *testing.T) {
	fs, err := NewFieldSelector("2-4,1")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if fs.maxField != 4 {
		t.Errorf("expected maxField=4, got %d", fs.maxField)
	}
}

// --- Extract tests ---

func TestExtract_SingleField(t *testing.T) {
	fs, _ := NewFieldSelector("1")
	got, err := fs.Extract("a:b:c", ":")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got != "a" {
		t.Errorf("expected 'a', got %q", got)
	}
}

func TestExtract_OneIndexed(t *testing.T) {
	// field 1 must return first word, not second
	fs, _ := NewFieldSelector("1")
	got, err := fs.Extract("first:second:third", ":")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got != "first" {
		t.Errorf("expected 'first', got %q", got)
	}
}

func TestExtract_MultipleFields(t *testing.T) {
	fs, _ := NewFieldSelector("1,3")
	got, err := fs.Extract("a:b:c", ":")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got != "a:c" {
		t.Errorf("expected 'a:c', got %q", got)
	}
}

func TestExtract_Range(t *testing.T) {
	fs, _ := NewFieldSelector("1-3")
	got, err := fs.Extract("a:b:c:d", ":")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got != "a:b:c" {
		t.Errorf("expected 'a:b:c', got %q", got)
	}
}

func TestExtract_LastField(t *testing.T) {
	// field == len(words) is valid with 1-indexing
	fs, _ := NewFieldSelector("3")
	got, err := fs.Extract("a:b:c", ":")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got != "c" {
		t.Errorf("expected 'c', got %q", got)
	}
}

func TestExtract_FieldOutOfBounds(t *testing.T) {
	fs, _ := NewFieldSelector("5")
	_, err := fs.Extract("a:b:c", ":")
	if !errors.Is(err, ErrFieldOutOfBounds) {
		t.Errorf("expected ErrFieldOutOfBounds, got %v", err)
	}
}

func TestExtract_DifferentDelimiter(t *testing.T) {
	fs, _ := NewFieldSelector("2")
	got, err := fs.Extract("a,b,c", ",")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got != "b" {
		t.Errorf("expected 'b', got %q", got)
	}
}

func TestExtract_OutputJoinedByDelimiter(t *testing.T) {
	fs, _ := NewFieldSelector("1,3")
	got, err := fs.Extract("a,b,c", ",")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got != "a,c" {
		t.Errorf("expected 'a,c', got %q", got)
	}
}

func TestExtract_SortedOutputRegardlessOfInputOrder(t *testing.T) {
	// fields stored sorted, so output order is always ascending
	fs, _ := NewFieldSelector("3,1")
	got, err := fs.Extract("a:b:c", ":")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got != "a:c" {
		t.Errorf("expected 'a:c', got %q", got)
	}
}
